### ISSUE TITLE
"pip install btchip-python" does not work, runs into error

### ISSUE THREAD

**Issue by SteffenIvanhoe** [LedgerHQ/btchip-python#23]
Here is what I get when trying to install it:

> pip install btchip-python
> Collecting btchip-python
> Collecting hidapi>=0.7.99 (from btchip-python)
>   Using cached hidapi-0.7.99.post20.tar.gz
> Collecting setuptools>=19.0 (from hidapi>=0.7.99->btchip-python)
>   Using cached setuptools-36.2.7-py2.py3-none-any.whl
> Building wheels for collected packages: hidapi
>   Running setup.py bdist_wheel for hidapi ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mXtvEp/hidapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp7zOcANpip-wheel- --python-tag cp27:
>   running bdist_wheel
>   running build
>   running build_ext
>   cythoning hid.pyx to hid.c
>   building 'hid' extension
>   creating build
>   creating build/temp.linux-x86_64-2.7
>   creating build/temp.linux-x86_64-2.7/hidapi
>   creating build/temp.linux-x86_64-2.7/hidapi/libusb
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python2.7 -c hid.c -o build/temp.linux-x86_64-2.7/hid.o
>   hid.c: In function ‘__pyx_pf_3hid_6device_open’:
>   hid.c:1720:45: warning: passing argument 1 of ‘PyUnicodeUCS4_AsWideChar’ from incompatible pointer type [-Wincompatible-pointer-types]
>          __pyx_v_result = PyUnicode_AsWideChar(__pyx_v_serial_number, __pyx_v_cserial_number, __pyx_v_serial_len);
>                                                ^
>   In file included from /usr/include/python2.7/Python.h:85:0,
>                    from hid.c:4:
>   /usr/include/python2.7/unicodeobject.h:246:31: note: expected ‘PyUnicodeObject * {aka struct <anonymous> *}’ but argument is of type ‘PyObject * {aka struct _object *}’
>     define PyUnicode_AsWideChar PyUnicodeUCS4_AsWideChar
>                                  ^
>   /usr/include/python2.7/unicodeobject.h:591:24: note: in expansion of macro ‘PyUnicode_AsWideChar’
>    PyAPI_FUNC(Py_ssize_t) PyUnicode_AsWideChar(
>                           ^
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python2.7 -c hidapi/libusb/hid.c -o build/temp.linux-x86_64-2.7/hidapi/libusb/hid.o
>   hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
>   compilation terminated.
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 

I tried to install with `sudo apt-get install python-btchip` but this only installs an older version which misses the attribute `enableAlternate2fa` which is needed by the referencing software!

**Comment by SteffenIvanhoe** [comment]
Today I tried again in another Windows box to install with the PIP from Python 3.6.2.
This installation failed again, if for a different reason then the one mentioned above:

C:\Users\Win7 VirtualBox>py -m pip install btchip-python
Collecting btchip-python
  Using cached btchip-python-0.1.21.tar.gz
Collecting hidapi>=0.7.99 (from btchip-python)
  Using cached hidapi-0.7.99.post20.tar.gz
    Complete output from command python setup.py egg_info:
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Plex\Scanners.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Plex\Actions.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Pythran.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Lexicon.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Scanning.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Parsing.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Visitor.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\FlowControl.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Compiler\Code.py because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Runtime\refnanny.pyx because it changed.
    Compiling C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-
0.27\Cython\Tempita\_tempita.py because it changed.
    [ 1/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Code.py
    [ 2/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\FlowControl.py
    [ 3/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Lexicon.py
    [ 4/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Parsing.py
    [ 5/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Pythran.py
    [ 6/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Scanning.py
    [ 7/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Compiler\Visitor.py
    [ 8/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Plex\Actions.py
    [ 9/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Plex\Scanners.py
    [10/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Runtime\refnanny.pyx
    [11/11] Cythonizing C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky3
5b\Cython-0.27\Cython\Tempita\_tempita.py
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc\*'
    warning: no files found matching '*.pyx' under directory 'Cython\Debugger\Te
sts'
    warning: no files found matching '*.pxd' under directory 'Cython\Debugger\Te
sts'
    warning: no files found matching '*.pxd' under directory 'Cython\Utility'
    Traceback (most recent call last):
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\msvc.py", line 477, in __init__
        self.vc_ver = self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\install_lib.py", line 11, in run
        self.build()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\command\install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\msvc.py", line 172, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\msvc.py", line 771, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\msvc.py", line 480, in __init__
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is requir
ed. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstud
io.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-0.
27\setup.py", line 278, in <module>
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Micro
soft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-buil
d-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\WIN7VI~1\AppData\Local\Temp\easy_install-o2fky35b\Cython-0.
27\setup.py", line 278, in <module>
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Micro
soft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-buil
d-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WIN7VI~1\AppData\Local\Temp\pip-build-gze5j6fp\hidapi\setup
.py", line 123, in <module>
        install_requires = ['setuptools>=19.0'],
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 1115, in build_and_insta
ll
        self.run_setup(setup_script, setup_base, args)
      File "C:\Users\Win7 VirtualBox\AppData\Local\Programs\Python\Python36\lib\
site-packages\setuptools\command\easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft V
isual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http
://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\WIN7VI~1
\AppData\Local\Temp\pip-build-gze5j6fp\hidapi\

**Comment by wupeaking** [comment]
I have the same issue.

pip install btchip-python
Collecting btchip-python
  Using cached https://files.pythonhosted.org/packages/66/26/52b88daa03da39cc8d7178f945af0dcbba46d642ced6ea56e305762568ae/btchip-python-0.1.28.tar.gz
Collecting hidapi>=0.7.99 (from btchip-python)
  Using cached https://files.pythonhosted.org/packages/c1/86/89df0e8890f96eeb5fb68d4ccb14cb38e2c2d2cfd7601ba972206acd9015/hidapi-0.7.99.post21.tar.gz
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/FusedNode.py because it changed.
    Compiling /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Tempita/_tempita.py because it changed.
    [1/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/FlowControl.py
    [2/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/FusedNode.py
    [3/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/Scanning.py
    [4/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Compiler/Visitor.py
    [5/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Plex/Actions.py
    [6/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Plex/Scanners.py
    [7/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Runtime/refnanny.pyx
    [8/8] Cythonizing /tmp/easy_install-LVx9WQ/Cython-0.29/Cython/Tempita/_tempita.py
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    warning: no files found matching 'pyximport/README'
    unable to execute gcc: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Lb9NpR/hidapi/setup.py", line 123, in <module>
        install_requires = ['setuptools>=19.0'],
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Lb9NpR/hidapi/
