### ISSUE TITLE
Can't open Ledger with the latest Bitcoin app selected

### ISSUE THREAD

**Issue by stepansnigirev** [LedgerHQ/btchip-python#48]
Bitcoin app version: 1.5.1 
OS: Ubuntu 20
hid detects Ledger, but open of the device fails.
This breaks communication with Ledger for HWI and Specter.

```
>>> from btchip import btchipComm
>>> btchipComm.getDongle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ss/dev/desktop/myspecter/.venv/lib/python3.8/site-packages/btchip/btchipComm.py", line 230, in getDongle
    dev.open_path(hidDevicePath)
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

**Comment by TamtamHero** [comment]
https://github.com/bitcoin-core/HWI/pull/403 should fix it

**Comment by stepansnigirev** [comment]
No, we already integrated that.

Enumeration works, I get correct path, but hid device can not be opened:
```
>>> import hid
>>> hid.enumerate()
[{'path': b'0001:0019:00', 'vendor_id': 11415, 'product_id': 4117, 'serial_number': '', 'release_number': 513, 'manufacturer_string': '', 'product_string': '', 'usage_page': 0, 'usage': 0, 'interface_number': 0}, {'path': b'0001:0019:01', 'vendor_id': 11415, 'product_id': 4117, 'serial_number': '', 'release_number': 513, 'manufacturer_string': '', 'product_string': '', 'usage_page': 0, 'usage': 0, 'interface_number': 1}, {'path': b'0001:0003:00', 'vendor_id': 1118, 'product_id': 1970, 'serial_number': '', 'release_number': 1862, 'manufacturer_string': '', 'product_string': '', 'usage_page': 0, 'usage': 0, 'interface_number': 0}, {'path': b'0001:0003:01', 'vendor_id': 1118, 'product_id': 1970, 'serial_number': '', 'release_number': 1862, 'manufacturer_string': '', 'product_string': '', 'usage_page': 0, 'usage': 0, 'interface_number': 1}, {'path': b'0001:0003:02', 'vendor_id': 1118, 'product_id': 1970, 'serial_number': '', 'release_number': 1862, 'manufacturer_string': '', 'product_string': '', 'usage_page': 0, 'usage': 0, 'interface_number': 2}]
>>> dev = hid.device()
>>> dev.open_path(b'0001:0019:00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

**Comment by TamtamHero** [comment]
This works just fine on my own Ubuntu 20.04 with python3/btchip 0.31.1/bitcoin 1.5.1/Firmware 1.6.1
`>>> from btchip import btchipComm
>>> btchipComm.getDongle()`

Try to use the other interface: `dev.open_path(b'0001:0019:01')` instead of `dev.open_path(b'0001:0019:00')`

**Comment by stepansnigirev** [comment]
Thanks, updating udev rules did it.

**Comment by ArttuPakarinen** [comment]
I have both BTC and ETH apps in my ledger device.

The following code does not run on my ubuntu when i have BTC app open, but it runs when i have ETH app open:

```
import TransportWebHID from "@ledgerhq/hw-transport-webhid";

const transport = await TransportWebHID.create();
```

The same code will run in Windows environment.
